const {chromium, expect} = require("../../frontend/node_modules/@playwright/test");
const AxeBuilder = require("../../frontend/node_modules/@axe-core/playwright").default;
const fs = require("node:fs");
const path = require("node:path");
const {pathToFileURL} = require("node:url");
(async()=>{
  fs.mkdirSync(".runtime/candidate-viewer-test",{recursive:true});
  const browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
  const page=await context.newPage(), errors=[];
  page.on("pageerror",e=>errors.push(e.message));
  page.on("dialog",dialog=>dialog.accept());
  const checks=[];
  for(const [source,kind,count] of [["meiwei","pair",1015],["dspcbsd","box",835]]) {
    const root=path.resolve(`ml/runs/${source}-visual-review-002`);
    await page.goto(pathToFileURL(path.join(root,"index.html")).href);
    await expect(page.getByRole("heading",{name:"PCB candidate review",exact:true})).toBeVisible();
    await expect(page.locator("#cases option")).toHaveCount(count);
    await page.locator("#kind").selectOption(kind);
    await expect(page.locator("#save")).toBeEnabled();
    await expect(page.locator("#images svg")).toHaveCount(source==="meiwei"?2:1);
    if(kind==="box") await expect(page.locator('rect[stroke-dasharray]')).toHaveCount(1);
    await page.locator("#zoom").selectOption("2");
    expect(await page.locator("#images svg").first().evaluate(el=>el.style.width)).toBe("200%");
    await page.locator("#overlays").uncheck(); await expect(page.locator("#images rect")).toHaveCount(0);
    await page.locator("#overlays").check(); await page.locator("#zoom").selectOption("1");
    await page.locator("#reviewer").fill("UI smoke test (synthetic)");
    await page.locator("#save").click(); await expect(page.locator("#message")).toContainText("Complete every answer");
    for(const select of await page.locator("#fields select").all()) await select.selectOption("needs_reference");
    await page.locator("#rationale").fill("Synthetic interface test only; no expert review performed.");
    await page.locator("#save").click(); await expect(page.locator("#progress")).toContainText("1 saved");
    await expect(page.locator("#reviewer")).toBeDisabled();
    const promise=page.waitForEvent("download"); await page.locator("#export").click();
    const download=await promise; const exported=path.resolve(`.runtime/candidate-viewer-test/${source}-synthetic.json`);
    await download.saveAs(exported);
    const batch=JSON.parse(fs.readFileSync(exported,"utf8"));expect(batch.decisions).toHaveLength(1);
    expect(batch.reviewer).toBe("UI smoke test (synthetic)");
    await page.locator("#clear").click();await expect(page.locator("#progress")).toContainText("0 saved");
    await page.locator("#import").setInputFiles(exported);await expect(page.locator("#message")).toContainText("Restored 1 decisions");
    const invalid={...batch,packet_sha256:"0".repeat(64)};
    const invalidPath=path.resolve(`.runtime/candidate-viewer-test/${source}-wrong-packet.json`);
    fs.writeFileSync(invalidPath,JSON.stringify(invalid));await page.locator("#import").setInputFiles(invalidPath);
    await expect(page.locator("#message")).toContainText("different packet");await expect(page.locator("#progress")).toContainText("1 saved");
    const conflict=structuredClone(batch);conflict.decisions[0].rationale="Conflicting synthetic rationale";
    fs.writeFileSync(invalidPath,JSON.stringify(conflict));await page.locator("#import").setInputFiles(invalidPath);
    await expect(page.locator("#message")).toContainText("Conflicting saved decision");
    await page.screenshot({path:`.runtime/candidate-viewer-test/${source}-desktop.png`,fullPage:true});
    await page.setViewportSize({width:390,height:844});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.screenshot({path:`.runtime/candidate-viewer-test/${source}-mobile.png`,fullPage:true});
    const accessibility=await new AxeBuilder({page}).analyze();expect(accessibility.violations).toEqual([]);
    await page.setViewportSize({width:1440,height:1000});
    checks.push({source,cases:count,images:true,zoom:true,overlays:true,validation:true,export_restore:true,
                 wrong_packet_rejected:true,conflict_rejected:true,mobile_overflow:false,axe_violations:0});
  }
  const broken=path.resolve(".runtime/candidate-viewer-test/missing-images");fs.mkdirSync(broken,{recursive:true});
  for(const file of ["index.html","candidate_viewer.js"])fs.copyFileSync(path.resolve("ml/runs/dspcbsd-visual-review-002",file),path.join(broken,file));
  await page.goto(pathToFileURL(path.join(broken,"index.html")).href);
  await expect(page.locator("#message")).toContainText("Image unavailable");await expect(page.locator("#save")).toBeDisabled();
  expect(errors).toEqual([]);await browser.close();
  const result={checks,missing_image_disables_save:true,page_errors:errors};
  fs.writeFileSync(".runtime/candidate-viewer-test/results.json",JSON.stringify(result,null,2));console.log(JSON.stringify(result));
})().catch(error=>{console.error(error);process.exit(1);});
